# Generated by Django 5.1.15 on 2026-09-05 15:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('insurer', models.CharField(max_length=80)),
                ('policy_number', models.CharField(blank=True, max_length=40, null=True)),
                ('insurer_claim_number', models.CharField(blank=True, max_length=40, null=True)),
                ('claims_handler', models.CharField(blank=True, max_length=120, null=True)),
                ('claim_type', models.CharField(max_length=60)),
                ('incident_date', models.DateField()),
                ('lodged_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('REGISTERED', 'Registered'), ('DOCS_REQUESTED', 'Docs Requested'), ('DOCS_RECEIVED', 'Docs Received'), ('ASSESSOR_APPOINTED', 'Assessor Appointed'), ('ASSESSMENT', 'Assessment'), ('DECISION', 'Decision'), ('OFFER', 'Offer'), ('ACCEPTED', 'Accepted'), ('PAID', 'Paid'), ('CLOSED', 'Closed')], default='REGISTERED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=16, unique=True)),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=60)),
                ('second_name', models.CharField(blank=True, max_length=60, null=True)),
                ('surname', models.CharField(max_length=60)),
                ('id_number', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'ID must be 13 digits')])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('licence_expiry', models.DateField(blank=True, null=True)),
                ('wedding_anniversary', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('client_since', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=80, null=True)),
                ('employer', models.CharField(blank=True, max_length=80, null=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=120, null=True)),
                ('primary_address', models.CharField(blank=True, max_length=255, null=True)),
                ('risk_profile', models.CharField(default='MODERATE', max_length=20)),
                ('risk_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['surname', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ReminderDismissal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crm.claim')),
            ],
            options={
                'ordering': ['recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='crm.client'),
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(max_length=30)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monthly_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('vehicle', models.CharField(blank=True, max_length=120, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='crm.client')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('creditor', models.CharField(blank=True, max_length=80, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='crm.client')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=80)),
                ('product_type', models.CharField(max_length=60)),
                ('policy_number', models.CharField(max_length=40)),
                ('sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('monthly_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='crm.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimSceneItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=40)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_items', to='crm.claim')),
            ],
            options={
                'unique_together': {('claim', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=40)),
                ('signed_on', models.DateField()),
                ('storage_key', models.CharField(blank=True, max_length=300, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.client')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client', 'type'), name='uq_client_compliance_type')],
            },
        ),
    ]
