# Generated by Django 5.1.15 on 2026-09-06 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_client_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='shared_with',
            field=models.ForeignKey(blank=True, help_text='Optional co-client (e.g. spouse or partner) sharing this wealth goal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_goals', to='crm.client'),
        ),
    ]
